### ISSUE TITLE
Add a project LICENSE

### ISSUE THREAD

**Issue by matshou** [yooksi/pz-icdp#1]
Choose an [open source license](https://choosealicense.com/) for the project.

The original author has explicitly stated that he retains exclusive copyright:

> This mod can only be added to and extended with the express permission from the original creator. Having received permission, credit must be given to the original creator, both within the files of the mod and wherever the mod roams online. If no permission is received you may not alter the mod, and it must be treated as a mod that is 'On Lockdown'.

The author has also given me permission to upload the code on Github which grants the following limited license:

> Any User-Generated Content you post publicly, including issues, comments, and contributions to other Users' repositories, may be viewed by others. By setting your repositories to be viewed publicly, you agree to allow others to view and "fork" your repositories (this means that others may make their own copies of Content from your repositories in repositories they control).

> If you set your pages and repositories to be viewed publicly, you grant each User of GitHub a nonexclusive, worldwide license to use, display, and perform Your Content through the GitHub Service and to reproduce Your Content solely on GitHub as permitted through GitHub's functionality (for example, through forking). 

Read what happens when a project is [not licensed](https://choosealicense.com/no-permission/).

**Comment by matshou** [comment]
An open-source license that is closest to the original author copyright statement would be a [Creative Commons](https://creativecommons.org/licenses/) license:

- **Attribution**: This license lets others distribute, remix, adapt, and build upon your work, even commercially, as long as they credit you for the original creation. This is the most accommodating of licenses offered. Recommended for maximum dissemination and use of licensed materials. 

- **Attribution-ShareAlike**: This license lets others remix, adapt, and build upon your work even for commercial purposes, as long as they credit you and license their new creations under the identical terms. This license is often compared to “copyleft” free and open source software licenses. All new works based on yours will carry the same license, so any derivatives will also allow commercial use. This is the license used by Wikipedia, and is recommended for materials that would benefit from incorporating content from Wikipedia and similarly licensed projects. 

- **Attribution-NoDerivs**: This license lets others reuse the work for any purpose, including commercially; however, it cannot be shared with others in adapted form, and credit must be provided to you. 

- **Attribution-NonCommercial**: This license lets others remix, adapt, and build upon your work non-commercially, and although their new works must also acknowledge you and be non-commercial, they don’t have to license their derivative works on the same terms. 

- **Attribution-NonCommercial-ShareAlike**: This license lets others remix, adapt, and build upon your work non-commercially, as long as they credit you and license their new creations under the identical terms. 

- **Attribution-NonCommercial-NoDerivs**: This license is the most restrictive of our six main licenses, only allowing others to download your works and share them with others as long as they credit you, but they can’t change them in any way or use them commercially.

**Comment by matshou** [comment]
@Nebula-ru I think it comes down to whether we want others to be able to use an adapted version of this project for commercial purposes (making money). We want to allow others to *distribute, remix, adapt, and build upon* our work since it is already on Github and we want them to give attribution (provide credits to you and optionally me), and I guess we could exclude the possibility of commercial application, what do you think?

**Comment by Nebula-ru** [comment]
Attribution-NonCommercial-ShareAlike: This license lets others remix, adapt, and build upon your work non-commercially, as long as they credit you and license their new creations under the identical terms.

**Comment by matshou** [comment]
According to CC FAQ the authors of the license recommend **against** using this type of license for software:

https://creativecommons.org/faq/#can-i-apply-a-creative-commons-license-to-software

> We do not recommend it. Creative Commons licenses should not be used for software. We strongly encourage you to use one of the very good software licenses which are already available. We recommend considering licenses made available by the Free Software Foundation or listed at the Open Source Initiative. Unlike our licenses, which do not make mention of source or object code, these existing licenses were designed specifically for use with software. Furthermore, our licenses are not compatible with the GPL, the most frequently used free software license.
